export const formSchema = {
  steps: [
    {
      step: 1,
      name: 'Organization Info',
      fields: [
        {
          id: 'industry',
          label: 'Industry',
          type: 'dropdown',
          required: true,
          helperText: 'Select your industry',
          options: ['D2C', 'SaaS', 'EdTech', 'Real Estate', 'Insurance', 'B2B Services'],
        },
        {
          id: 'company_name',
          label: 'Company Name',
          type: 'text',
          required: true,
          helperText: 'Full legal name of your company',
        },
        {
          id: 'website_url',
          label: 'Website URL',
          type: 'url',
          required: true,
          helperText: 'e.g., https://brand.com',
        },
        {
          id: 'hq_location',
          label: 'Headquarters Location',
          type: 'text',
          required: false,
          helperText: 'City & Country',
        },
        {
          id: 'description',
          label: 'Company Description',
          type: 'textarea',
          required: false,
          helperText: 'Short description of what you do',
        },
      ],
    },
    {
      step: 2,
      name: 'Content Inventory (Dynamic)',
      fields: [
        {
          id: 'product_catalog',
          label: 'Product Catalog Upload',
          type: 'file',
          required: true,
          helperText: 'Upload CSV with SKU, Name, Category, URL, Description',
          visibleIf: { industry: 'D2C' },
        },
        {
          id: 'marketplace_listings',
          label: 'Marketplace Listings',
          type: 'file',
          required: false,
          helperText: 'Upload marketplace CSV (Amazon, Flipkart, etc.)',
          visibleIf: { industry: 'D2C' },
        },
        {
          id: 'programs_courses',
          label: 'Programs / Courses',
          type: 'file',
          required: true,
          helperText: 'Upload CSV of academic programs/courses',
          visibleIf: { industry: 'EdTech' },
        },
        {
          id: 'features_modules',
          label: 'Features / Modules',
          type: 'textarea',
          required: true,
          helperText: 'List features of your platform or app',
          visibleIf: { industry: ['SaaS', 'EdTech'] },
        },
        {
          id: 'service_list',
          label: 'Service List',
          type: 'file',
          required: true,
          helperText: 'Upload CSV of services you offer (Name, Desc, URL)',
          visibleIf: { industry: ['B2B Services', 'Insurance'] },
        },
        {
          id: 'service_areas',
          label: 'Service Areas',
          type: 'textarea',
          required: true,
          helperText: 'List of cities/regions you operate in',
          visibleIf: { industry: ['Real Estate', 'Insurance'] },
        },
        {
          id: 'case_studies',
          label: 'Case Studies / Portfolio',
          type: 'textarea',
          required: false,
          helperText: 'Links to case studies or notable clients',
          visibleIf: { industry: ['SaaS', 'B2B Services'] },
        },
      ],
    },
  ],
}
